import {ServiceRepo} from './models/Service.js';
const data=[
{name:'Wedding',slug:'wedding',description:'Photography, films and reception experiences for weddings.',displayOrder:1,subServices:[
{name:'Wedding Photography',optionGroups:[{name:'Photography Style',options:[{name:'Traditional Photography'},{name:'Candid Photography'},{name:'Traditional + Candid'}]}]},
{name:'Wedding Videography',optionGroups:[{name:'Video Style',options:[{name:'Traditional Video'},{name:'Cinematic Video'},{name:'Documentary Style'}]}]},
{name:'Reception Photography',optionGroups:[{name:'Coverage',options:[{name:'Traditional'},{name:'Candid'},{name:'Traditional + Candid'}]}]},
{name:'Reception Videography',optionGroups:[{name:'Video',options:[{name:'Traditional Video'},{name:'Cinematic Video'}]}]},
{name:'Wedding 360° Video',optionGroups:[{name:'Duration',options:[{name:'1 Hour'},{name:'2 Hours'},{name:'3 Hours'},{name:'Custom'}]}]},
{name:'360° Camera Booth',optionGroups:[{name:'Booth Options',options:[{name:'Props'},{name:'Instant Sharing'},{name:'Custom Overlay'},{name:'Slow Motion'}]}]},
{name:'Drone Coverage',optionGroups:[{name:'Coverage',options:[{name:'Ceremony'},{name:'Venue'},{name:'Full Event'}]}]},
{name:'Live Streaming',optionGroups:[{name:'Platform',options:[{name:'YouTube'},{name:'Private Link'},{name:'Custom'}]}]},
{name:'Wedding Album',optionGroups:[{name:'Album',options:[{name:'Standard'},{name:'Premium'},{name:'Custom'}]}]},
{name:'Photo Frames',optionGroups:[{name:'Frame',options:[{name:'Wooden'},{name:'Acrylic'},{name:'Glass'},{name:'Metal'},{name:'Canvas'}]}]}
],addOns:[{name:'Extra Photographer'},{name:'Extra Videographer'},{name:'Drone'},{name:'Live Streaming'},{name:'Album'},{name:'Photo Frame'}]},
{name:'Pre-Wedding',slug:'pre-wedding',description:'Flexible couple photography and cinematic pre-wedding films.',displayOrder:2,subServices:[
{name:'Pre-Wedding Photography',optionGroups:[{name:'Style',options:[{name:'Traditional'},{name:'Candid'},{name:'Cinematic'}]},{name:'Location',options:[{name:'Studio'},{name:'Outdoor'},{name:'Multiple Locations'}]}]},
{name:'Pre-Wedding Videography',optionGroups:[{name:'Video',options:[{name:'Cinematic Video'},{name:'Story-based Video'},{name:'Couple Cinematic'},{name:'Highlight Video'}]},{name:'Deliverables',options:[{name:'Teaser'},{name:'Save-the-Date Video'},{name:'Highlight Video'},{name:'Full Video'},{name:'Instagram Reel'}]}]},
{name:'Photography + Videography',optionGroups:[{name:'Coverage',options:[{name:'Half Day'},{name:'Full Day'},{name:'Multiple Days'}]}]}
],addOns:[{name:'Drone'},{name:'Extra Photographer'},{name:'Extra Videographer'},{name:'Makeup & Styling'},{name:'Costume / Outfit Changes'},{name:'Props'},{name:'Album'}]},
{name:'Engagement',slug:'engagement',description:'Engagement ceremony and couple coverage.',displayOrder:3,subServices:[{name:'Engagement Photography',optionGroups:[{name:'Style',options:[{name:'Traditional'},{name:'Candid'},{name:'Both'}]}]},{name:'Engagement Videography',optionGroups:[{name:'Video',options:[{name:'Traditional'},{name:'Cinematic'},{name:'Highlight'}]}]}],addOns:[{name:'Drone'},{name:'Album'},{name:'Frames'}]},
{name:'Birthday',slug:'birthday',description:'Birthday and celebration coverage.',displayOrder:4,subServices:[{name:'Birthday Photography',optionGroups:[{name:'Style',options:[{name:'Traditional'},{name:'Candid'}]}]},{name:'Birthday Videography',optionGroups:[{name:'Video',options:[{name:'Traditional'},{name:'Cinematic'},{name:'Highlight'}]}]},{name:'360° Camera Booth',optionGroups:[{name:'Extras',options:[{name:'Props'},{name:'Instant Sharing'}]}]}],addOns:[{name:'Photo Booth'},{name:'Cake Smash'},{name:'Album'},{name:'Frames'}]},
{name:'Maternity',slug:'maternity',description:'Studio and outdoor maternity sessions.',displayOrder:5,subServices:[{name:'Studio Maternity',optionGroups:[{name:'Type',options:[{name:'Solo'},{name:'Couple'},{name:'Family'}]}]},{name:'Outdoor Maternity',optionGroups:[{name:'Location',options:[{name:'Outdoor'},{name:'Customer Location'},{name:'Multiple Locations'}]}]}],addOns:[{name:'Makeup & Styling'},{name:'Album'},{name:'Frames'},{name:'Canvas Print'}]},
{name:'Baby & Kids',slug:'baby-kids',description:'Newborn, baby, kids and milestone sessions.',displayOrder:6,subServices:[{name:'Newborn Shoot'},{name:'Baby Portrait'},{name:'Cake Smash'},{name:'1st Birthday'},{name:'Kids Portrait'},{name:'Family + Baby'}],addOns:[{name:'Album'},{name:'Frames'},{name:'Canvas Print'}]},
{name:'Portrait',slug:'portrait',description:'Individual, couple, family, professional and editorial portraits.',displayOrder:7,subServices:[{name:'Individual Portrait',optionGroups:[{name:'Frame',options:[{name:'No Frame'},{name:'Wooden'},{name:'Acrylic'},{name:'Glass'},{name:'Metal'},{name:'Canvas'}]},{name:'Print Size',options:[{name:'6 × 8'},{name:'8 × 12'},{name:'12 × 18'},{name:'Custom'}]}]},{name:'Couple Portrait'},{name:'Family Portrait'},{name:'Professional / Corporate Portrait'},{name:'Fashion Portrait'}],addOns:[{name:'Retouching'},{name:'Extra Photos'},{name:'Extra Outfit'},{name:'Background Selection'}]},
{name:'Corporate',slug:'corporate',description:'Headshots, teams, events and business films.',displayOrder:8,subServices:[{name:'Corporate Headshots'},{name:'Team Photography'},{name:'Office Photography'},{name:'Corporate Event Photography'},{name:'Product Photography'},{name:'Promotional Video'},{name:'Interview Video'},{name:'Drone Coverage'},{name:'Live Streaming'}],addOns:[{name:'Extra Photographer'},{name:'Extra Videographer'},{name:'Retouching'},{name:'Same-day Delivery'}]}
];
export async function seedServices(){const existing=await ServiceRepo.find();if(existing.length)return;for(const x of data)await ServiceRepo.create(x);console.log(`🟩 Seeded ${data.length} booking services.`)}
