import React,{useEffect,useMemo,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowLeft,ArrowRight,Check,CalendarDays,Clock3,Send} from 'lucide-react';
import API from '../services/api';import {Navbar} from '../components/Navbar';import {Footer} from '../components/Footer';
const steps=['Service','Options','Date & time','Event','Your details','Review'];
export const Booking=()=>{
 const [params]=useSearchParams();const [services,setServices]=useState([]);const [step,setStep]=useState(0);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [done,setDone]=useState(null);const [error,setError]=useState('');
 const [form,setForm]=useState({service:null,subService:null,package:null,selections:[],addOns:[],event:{date:'',alternateDate:'',startTime:'',endTime:'',location:'',city:'',guestCount:'',budget:'',notes:''},customer:{name:'',email:'',phone:'',alternatePhone:''}});
 useEffect(()=>{API.get('/services').then(r=>{setServices(r.data||[]);const wanted=params.get('category');if(wanted){const found=(r.data||[]).find(x=>x.slug===wanted||x.name.toLowerCase().replace(/\s+/g,'-')===wanted);if(found)setForm(f=>({...f,service:found}))}}).catch(()=>setError('Could not load booking services.')).finally(()=>setLoading(false))},[]);
 const subs=form.service?.subServices||[];const currentSub=subs.find(s=>s._id===form.subService?._id)||form.subService;const selectedKeys=new Set(form.selections.map(x=>`${x.group}:${x.name}`));
 const toggle=(group,opt)=>setForm(f=>{const key=`${group}:${opt.name}`;const exists=f.selections.some(x=>`${x.group}:${x.name}`===key);return {...f,selections:exists?f.selections.filter(x=>`${x.group}:${x.name}`!==key):[...f.selections,{group,name:opt.name,value:opt.name}]}});
 const valid=()=>{if(step===0)return !!form.service&&!!form.subService;if(step===2)return !!form.event.date&&!!form.event.startTime&&!!form.event.endTime;if(step===4)return !!form.customer.name&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.customer.email)&&!!form.customer.phone;return true};
 const next=()=>{setError('');if(!valid()){setError('Please complete the required fields.');return}setStep(s=>Math.min(5,s+1))};
 const submit=async()=>{setError('');if(!valid()){setError('Please complete the required fields.');return}setBusy(true);try{const r=await API.post('/bookings',form);setDone(r.data)}catch(e){setError(e.response?.data?.msg||'Could not submit booking request.')}finally{setBusy(false)}};
 if(loading)return <div className="endless-page"><Navbar/><main className="endless-shell py-24 text-center">Loading booking options…</main></div>;
 if(done)return <div className="endless-page"><Navbar/><main className="endless-shell py-20 min-h-[70vh] grid place-items-center"><div className="max-w-xl text-center"><div className="mx-auto w-16 h-16 rounded-full bg-[#d7a26d] grid place-items-center"><Check/></div><p className="text-[10px] uppercase tracking-[.3em] text-[#9a6845] font-bold mt-7">Request received</p><h1 className="endless-serif text-5xl mt-3">Your date is in the studio queue.</h1><p className="text-[#77766f] leading-7 mt-5">Reference <strong>{done.bookingId}</strong>. {done.conflict?'The requested slot already has activity, so our team will review the possibility and contact you.':'Our team will review your request and contact you with confirmation or the next step.'}</p><Link to="/" className="inline-flex mt-8 rounded-full bg-[#1f211e] text-white px-6 py-3 font-bold">Back to ENDLESS Moments</Link></div></main><Footer/></div>;
 return <div className="endless-page"><Navbar/><main className="endless-shell py-12 sm:py-16"><div className="max-w-5xl mx-auto"><Link to="/" className="inline-flex gap-2 items-center text-xs font-bold text-[#77766f]"><ArrowLeft size={15}/> Back</Link><div className="mt-8"><p className="text-[10px] uppercase tracking-[.35em] text-[#9a6845] font-bold">ENDLESS Moments booking</p><h1 className="endless-serif text-5xl sm:text-7xl leading-[.9] mt-3">Build your session.</h1><p className="text-[#77766f] mt-5 max-w-2xl leading-7">Choose exactly what you need. If another booking already occupies your preferred time, you can still request it and the studio will check whether the team can accommodate you.</p></div>
 <div className="flex overflow-auto gap-2 mt-10 pb-2">{steps.map((x,i)=><div key={x} className={`shrink-0 px-4 py-2 rounded-full text-xs font-bold ${i===step?'bg-[#1f211e] text-white':'bg-[#ebe5db] text-[#77766f]'}`}>{i+1}. {x}</div>)}</div>
 <section className="endless-card rounded-[2rem] p-5 sm:p-9 mt-5">
 {step===0&&<div><h2 className="text-2xl font-extrabold">What are you planning?</h2><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-6">{services.map(s=><button key={s._id} onClick={()=>setForm(f=>({...f,service:s,subService:null,package:null,selections:[],addOns:[]}))} className={`text-left rounded-2xl border p-5 transition ${form.service?._id===s._id?'border-[#9a6845] bg-[#f4eadf]':'border-[#ded8cd] bg-[#fffdf9] hover:border-[#bda487]'}`}><p className="font-bold">{s.name}</p><p className="text-sm text-[#77766f] mt-2 leading-6">{s.description}</p></button>)}</div>{form.service&&<div className="mt-8"><h3 className="font-bold">Choose a service within {form.service.name}</h3><div className="grid sm:grid-cols-2 gap-3 mt-4">{subs.map(s=><button key={s._id} onClick={()=>setForm(f=>({...f,subService:s,selections:[],addOns:[]}))} className={`text-left rounded-xl border p-4 ${form.subService?._id===s._id?'border-[#9a6845] bg-[#f4eadf]':'border-[#ded8cd]'}`}><span className="font-semibold">{s.name}</span></button>)}</div></div>}</div>}
 {step===1&&<div><h2 className="text-2xl font-extrabold">Customize your request</h2><p className="text-sm text-[#77766f] mt-2">Only options configured for {currentSub?.name} are shown.</p><div className="space-y-7 mt-7">{(currentSub?.optionGroups||[]).map(g=><div key={g.name}><h3 className="font-bold">{g.name}</h3><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-3">{g.options.map(o=><label key={o._id} className="flex gap-3 items-center rounded-xl border border-[#ded8cd] p-4 cursor-pointer"><input type={g.type==='single'?'radio':'checkbox'} name={g.type==='single'?g.name:undefined} checked={selectedKeys.has(`${g.name}:${o.name}`)} onChange={()=>toggle(g.name,o)}/><span className="text-sm font-semibold">{o.name}</span></label>)}</div></div>)}{(form.service?.addOns||[]).length>0&&<div><h3 className="font-bold">Add-ons</h3><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-3">{form.service.addOns.map(o=><label key={o._id} className="flex gap-3 items-center rounded-xl border border-[#ded8cd] p-4 cursor-pointer"><input type="checkbox" checked={form.addOns.some(x=>x.name===o.name)} onChange={()=>setForm(f=>({...f,addOns:f.addOns.some(x=>x.name===o.name)?f.addOns.filter(x=>x.name!==o.name):[...f.addOns,{group:'Add-on',name:o.name,value:o.name}]}))}/><span className="text-sm font-semibold">{o.name}</span></label>)}</div></div>}</div></div>}
 {step===2&&<div><h2 className="text-2xl font-extrabold">Preferred date & time</h2><p className="text-sm text-[#77766f] mt-2">A busy slot can still be requested; the studio will review capacity.</p><div className="grid sm:grid-cols-2 gap-4 mt-7"><Field label="Preferred date"><input type="date" value={form.event.date} min={new Date().toISOString().slice(0,10)} onChange={e=>setForm(f=>({...f,event:{...f.event,date:e.target.value}}))}/></Field><Field label="Alternate date"><input type="date" value={form.event.alternateDate} onChange={e=>setForm(f=>({...f,event:{...f.event,alternateDate:e.target.value}}))}/></Field><Field label="Start time"><input type="time" value={form.event.startTime} onChange={e=>setForm(f=>({...f,event:{...f.event,startTime:e.target.value}}))}/></Field><Field label="End time"><input type="time" value={form.event.endTime} onChange={e=>setForm(f=>({...f,event:{...f.event,endTime:e.target.value}}))}/></Field></div></div>}
 {step===3&&<div><h2 className="text-2xl font-extrabold">Tell us about the event</h2><div className="grid sm:grid-cols-2 gap-4 mt-7"><Field label="Venue / location"><input value={form.event.location} onChange={e=>setForm(f=>({...f,event:{...f.event,location:e.target.value}}))} placeholder="Venue or location"/></Field><Field label="City"><input value={form.event.city} onChange={e=>setForm(f=>({...f,event:{...f.event,city:e.target.value}}))} placeholder="City"/></Field><Field label="Guest count"><input value={form.event.guestCount} onChange={e=>setForm(f=>({...f,event:{...f.event,guestCount:e.target.value}}))} placeholder="Approx. people"/></Field><Field label="Budget (optional)"><input value={form.event.budget} onChange={e=>setForm(f=>({...f,event:{...f.event,budget:e.target.value}}))} placeholder="Budget range"/></Field></div><Field label="Additional requirements"><textarea rows="6" value={form.event.notes} onChange={e=>setForm(f=>({...f,event:{...f.event,notes:e.target.value}}))} placeholder="Tell the studio anything important…"/></Field></div>}
 {step===4&&<div><h2 className="text-2xl font-extrabold">How should we contact you?</h2><div className="grid sm:grid-cols-2 gap-4 mt-7"><Field label="Full name"><input value={form.customer.name} onChange={e=>setForm(f=>({...f,customer:{...f.customer,name:e.target.value}}))}/></Field><Field label="Email"><input type="email" value={form.customer.email} onChange={e=>setForm(f=>({...f,customer:{...f.customer,email:e.target.value}}))}/></Field><Field label="Phone"><input value={form.customer.phone} onChange={e=>setForm(f=>({...f,customer:{...f.customer,phone:e.target.value}}))}/></Field><Field label="Alternate phone"><input value={form.customer.alternatePhone} onChange={e=>setForm(f=>({...f,customer:{...f.customer,alternatePhone:e.target.value}}))}/></Field></div></div>}
 {step===5&&<div><h2 className="text-2xl font-extrabold">Review your request</h2><div className="mt-6 grid sm:grid-cols-2 gap-3"><Review label="Service" value={`${form.service?.name} / ${form.subService?.name||'General'}`}/><Review label="Date" value={`${form.event.date} · ${form.event.startTime}–${form.event.endTime}`}/><Review label="Customer" value={`${form.customer.name} · ${form.customer.phone}`}/><Review label="Location" value={`${form.event.location||'Not specified'}${form.event.city?`, ${form.event.city}`:''}`}/></div><div className="mt-4 rounded-2xl bg-[#eee8de] p-5"><p className="text-xs font-bold uppercase tracking-wider">Selections</p><p className="text-sm mt-2">{form.selections.map(x=>x.name).join(', ')||'No extra options selected'}{form.addOns.length?` · Add-ons: ${form.addOns.map(x=>x.name).join(', ')}`:''}</p></div></div>}
 {error&&<div className="mt-6 rounded-xl bg-red-50 text-red-700 p-4 text-sm">{error}</div>}
 <div className="flex justify-between gap-3 mt-9 pt-6 border-t border-[#ded8cd]"><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0||busy} className="rounded-full border border-[#d9d2c6] px-5 py-3 text-sm font-bold disabled:opacity-40">Back</button>{step<5?<button onClick={next} className="rounded-full bg-[#1f211e] text-white px-6 py-3 text-sm font-bold flex items-center gap-2">Continue <ArrowRight size={15}/></button>:<button onClick={submit} disabled={busy} className="rounded-full bg-[#1f211e] text-white px-6 py-3 text-sm font-bold flex items-center gap-2 disabled:opacity-60">{busy?'Submitting…':'Submit booking request'} <Send size={15}/></button>}</div>
 </section></div></main><Footer/></div>
};
const Field=({label,children})=><label className="block sm:col-span-1 mb-4"><span className="block text-[10px] uppercase tracking-[.2em] font-bold text-[#77766f] mb-2">{label}</span>{React.cloneElement(children,{className:'w-full rounded-xl border border-[#d9d2c6] bg-[#fffdf9] px-4 py-3.5 text-sm outline-none focus:border-[#9a6845]'})}</label>;
const Review=({label,value})=><div className="rounded-xl border border-[#ded8cd] p-4"><p className="text-[10px] uppercase tracking-wider text-[#9a6845] font-bold">{label}</p><p className="text-sm font-semibold mt-2">{value}</p></div>;
